/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6592. Copyright MediaTek Inc. (C) 2013.
 * Sat Jun 28 15:01:11 2014
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_MSDC1     GPIO_VMC
#define GPIO_DVDD28_MSDC2     GPIO_VIO18
#define GPIO_DVDD28_BPI     GPIO_VIO18


