/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6592. Copyright MediaTek Inc. (C) 2013.
 * Thu Feb 27 16:14:52 2014
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


