/* generated by mediatek */

package com.mediatek.common.featureoption;

public final class FeatureOption
{
    /**
     * check if GEMINI is turned on or not
     */
    public static final boolean MTK_GEMINI_SUPPORT = true;
    /**
     * check if MTK_AUDIO_PROFILES is turned on or not
     */
    public static final boolean MTK_AUDIO_PROFILES = true;
    /**
     * check if MTK_AUDENH_SUPPORT is turned on or not
     */
    public static final boolean MTK_AUDENH_SUPPORT = true;
    /**
     * check if MTK_BT_PROFILE_AVRCP13 is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_AVRCP13 = false;
    /**
     * check if MTK_GEMINI_ENHANCEMENT is turned on or not
     */
    public static final boolean MTK_GEMINI_ENHANCEMENT = true;
    /**
     * check if MTK_MEMORY_COMPRESSION_SUPPORT is turned on or not
     */
    public static final boolean MTK_MEMORY_COMPRESSION_SUPPORT = true;
    /**
     * check if MTK_LCA_SUPPORT is turned on or not
     */
    public static final boolean MTK_LCA_SUPPORT = false;
    /**
     * check if MTK_WAPI_SUPPORT is turned on or not
     */
    public static final boolean MTK_WAPI_SUPPORT = true;
    /**
     * check if MTK_QVGA_LANDSCAPE_SUPPORT is turned on or not
     */
    public static final boolean MTK_QVGA_LANDSCAPE_SUPPORT = false;
    /**
     * check if MTK_BT_SUPPORT is turned on or not
     */
    public static final boolean MTK_BT_SUPPORT = true;
    /**
     * check if MTK_WAPPUSH_SUPPORT is turned on or not
     */
    public static final boolean MTK_WAPPUSH_SUPPORT = true;
    /**
     * check if HAVE_APPC_FEATURE is turned on or not
     */
    public static final boolean HAVE_APPC_FEATURE = false;
    /**
     * check if MTK_AGPS_APP is turned on or not
     */
    public static final boolean MTK_AGPS_APP = true;
    /**
     * check if MTK_YGPS_APP is turned on or not
     */
    public static final boolean MTK_YGPS_APP = true;
    /**
     * check if MTK_OOBE_APP is turned on or not
     */
    public static final boolean MTK_OOBE_APP = false;
    /**
     * check if MTK_SCREEN_OFF_WIFI_OFF is turned on or not
     */
    public static final boolean MTK_SCREEN_OFF_WIFI_OFF = false;
    /**
     * check if MTK_FM_TX_SUPPORT is turned on or not
     */
    public static final boolean MTK_FM_TX_SUPPORT = false;
    /**
     * check if MTK_VT3G324M_SUPPORT is turned on or not
     */
    public static final boolean MTK_VT3G324M_SUPPORT = true;
    /**
     * check if MTK_VOICE_UI_SUPPORT is turned on or not
     */
    public static final boolean MTK_VOICE_UI_SUPPORT = true;
    /**
     * check if MTK_VOICE_UNLOCK_SUPPORT is turned on or not
     */
    public static final boolean MTK_VOICE_UNLOCK_SUPPORT = true;
    /**
     * check if MTK_MT519X_FM_SUPPORT is turned on or not
     */
    public static final boolean MTK_MT519X_FM_SUPPORT = false;
    /**
     * check if MTK_DM_APP is turned on or not
     */
    public static final boolean MTK_DM_APP = false;
    /**
     * check if MTK_MATV_ANALOG_SUPPORT is turned on or not
     */
    public static final boolean MTK_MATV_ANALOG_SUPPORT = true;
    /**
     * check if MTK_WLAN_SUPPORT is turned on or not
     */
    public static final boolean MTK_WLAN_SUPPORT = true;
    /**
     * check if MTK_IPO_SUPPORT is turned on or not
     */
    public static final boolean MTK_IPO_SUPPORT = true;
    /**
     * check if MTK_IPOH_SUPPORT is turned on or not
     */
    public static final boolean MTK_IPOH_SUPPORT = true;
    /**
     * check if MTK_GPS_SUPPORT is turned on or not
     */
    public static final boolean MTK_GPS_SUPPORT = true;
    /**
     * check if MTK_OMACP_SUPPORT is turned on or not
     */
    public static final boolean MTK_OMACP_SUPPORT = true;
    /**
     * check if MTK_BT_30_HS_SUPPORT is turned on or not
     */
    public static final boolean MTK_BT_30_HS_SUPPORT = false;
    /**
     * check if HAVE_MATV_FEATURE is turned on or not
     */
    public static final boolean HAVE_MATV_FEATURE = false;
    /**
     * check if MTK_BT_21_SUPPORT is turned on or not
     */
    public static final boolean MTK_BT_21_SUPPORT = true;
    /**
     * check if MTK_BT_30_SUPPORT is turned on or not
     */
    public static final boolean MTK_BT_30_SUPPORT = true;
    /**
     * check if MTK_BT_40_SUPPORT is turned on or not
     */
    public static final boolean MTK_BT_40_SUPPORT = true;
    /**
     * check if MTK_BT_FM_OVER_BT_VIA_CONTROLLER is turned on or not
     */
    public static final boolean MTK_BT_FM_OVER_BT_VIA_CONTROLLER = false;
    /**
     * check if MTK_BT_PROFILE_OPP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_OPP = true;
    /**
     * check if MTK_BT_PROFILE_SIMAP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_SIMAP = false;
    /**
     * check if MTK_BT_PROFILE_PRXM is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_PRXM = false;
    /**
     * check if MTK_BT_PROFILE_PRXR is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_PRXR = false;
    /**
     * check if MTK_BT_PROFILE_HIDH is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_HIDH = true;
    /**
     * check if MTK_BT_PROFILE_FTP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_FTP = false;
    /**
     * check if MTK_BT_PROFILE_PBAP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_PBAP = true;
    /**
     * check if MTK_BT_PROFILE_MANAGER is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_MANAGER = true;
    /**
     * check if MTK_BT_PROFILE_BPP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_BPP = false;
    /**
     * check if MTK_BT_PROFILE_BIP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_BIP = false;
    /**
     * check if MTK_BT_PROFILE_DUN is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_DUN = false;
    /**
     * check if MTK_BT_PROFILE_PAN is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_PAN = true;
    /**
     * check if MTK_BT_PROFILE_HFP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_HFP = true;
    /**
     * check if MTK_BT_PROFILE_A2DP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_A2DP = true;
    /**
     * check if MTK_BT_PROFILE_AVRCP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_AVRCP = true;
    /**
     * check if MTK_BT_PROFILE_AVRCP14 is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_AVRCP14 = false;
    /**
     * check if MTK_BT_PROFILE_TIMEC is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_TIMEC = false;
    /**
     * check if MTK_BT_PROFILE_TIMES is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_TIMES = false;
    /**
     * check if MTK_BT_PROFILE_MAPS is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_MAPS = false;
    /**
     * check if MTK_BT_PROFILE_MAPC is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_MAPC = false;
    /**
     * check if MTK_BT_PROFILE_SPP is turned on or not
     */
    public static final boolean MTK_BT_PROFILE_SPP = true;
    /**
     * check if MTK_DEDICATEDAPN_SUPPORT is turned on or not
     */
    public static final boolean MTK_DEDICATEDAPN_SUPPORT = false;
    /**
     * check if MTK_SEARCH_DB_SUPPORT is turned on or not
     */
    public static final boolean MTK_SEARCH_DB_SUPPORT = true;
    /**
     * check if MTK_DIALER_SEARCH_SUPPORT is turned on or not
     */
    public static final boolean MTK_DIALER_SEARCH_SUPPORT = true;
    /**
     * check if MTK_DHCPV6C_WIFI is turned on or not
     */
    public static final boolean MTK_DHCPV6C_WIFI = true;
    /**
     * check if MTK_FM_SHORT_ANTENNA_SUPPORT is turned on or not
     */
    public static final boolean MTK_FM_SHORT_ANTENNA_SUPPORT = false;
    /**
     * check if MTK_MDLOGGER_SUPPORT is turned on or not
     */
    public static final boolean MTK_MDLOGGER_SUPPORT = true;
    /**
     * check if MTK_TTY_SUPPORT is turned on or not
     */
    public static final boolean MTK_TTY_SUPPORT = true;
    /**
     * check if MTK_WB_SPEECH_SUPPORT is turned on or not
     */
    public static final boolean MTK_WB_SPEECH_SUPPORT = true;
    /**
     * check if MTK_WPA2PSK_SUPPORT is turned on or not
     */
    public static final boolean MTK_WPA2PSK_SUPPORT = false;
    /**
     * check if MTK_DUAL_MIC_SUPPORT is turned on or not
     */
    public static final boolean MTK_DUAL_MIC_SUPPORT = false;
    /**
     * check if HAVE_AWBENCODE_FEATURE is turned on or not
     */
    public static final boolean HAVE_AWBENCODE_FEATURE = true;
    /**
     * check if HAVE_AACENCODE_FEATURE is turned on or not
     */
    public static final boolean HAVE_AACENCODE_FEATURE = true;
    /**
     * check if MTK_WIFI_HOTSPOT_SUPPORT is turned on or not
     */
    public static final boolean MTK_WIFI_HOTSPOT_SUPPORT = true;
    /**
     * check if MTK_CTA_SUPPORT is turned on or not
     */
    public static final boolean MTK_CTA_SUPPORT = false;
    /**
     * check if MTK_FM_SUPPORT is turned on or not
     */
    public static final boolean MTK_FM_SUPPORT = true;
    /**
     * check if MTK_DM_ENTRY_DISPLAY is turned on or not
     */
    public static final boolean MTK_DM_ENTRY_DISPLAY = false;
    /**
     * check if MTK_THEMEMANAGER_APP is turned on or not
     */
    public static final boolean MTK_THEMEMANAGER_APP = true;
    /**
     * check if MTK_PHONE_VT_MM_RINGTONE is turned on or not
     */
    public static final boolean MTK_PHONE_VT_MM_RINGTONE = false;
    /**
     * check if MTK_PHONE_VT_VOICE_ANSWER is turned on or not
     */
    public static final boolean MTK_PHONE_VT_VOICE_ANSWER = false;
    /**
     * check if MTK_PHONE_VOICE_RECORDING is turned on or not
     */
    public static final boolean MTK_PHONE_VOICE_RECORDING = true;
    /**
     * check if MTK_POWER_SAVING_SWITCH_UI_SUPPORT is turned on or not
     */
    public static final boolean MTK_POWER_SAVING_SWITCH_UI_SUPPORT = true;
    /**
     * check if MTK_FD_SUPPORT is turned on or not
     */
    public static final boolean MTK_FD_SUPPORT = true;
    /**
     * check if MTK_DRM_APP is turned on or not
     */
    public static final boolean MTK_DRM_APP = true;
    /**
     * check if MTK_VLW_APP is turned on or not
     */
    public static final boolean MTK_VLW_APP = false;
    /**
     * check if MTK_SMS_FILTER_SUPPORT is turned on or not
     */
    public static final boolean MTK_SMS_FILTER_SUPPORT = true;
    /**
     * check if MTK_GEMINI_3G_SWITCH is turned on or not
     */
    public static final boolean MTK_GEMINI_3G_SWITCH = true;
    /**
     * check if MTK_IPV6_SUPPORT is turned on or not
     */
    public static final boolean MTK_IPV6_SUPPORT = true;
    /**
     * check if MTK_MULTI_STORAGE_SUPPORT is turned on or not
     */
    public static final boolean MTK_MULTI_STORAGE_SUPPORT = true;
    /**
     * check if MTK_MTKLOGGER_SUPPORT is turned on or not
     */
    public static final boolean MTK_MTKLOGGER_SUPPORT = true;
    /**
     * check if MTK_EMULATOR_SUPPORT is turned on or not
     */
    public static final boolean MTK_EMULATOR_SUPPORT = false;
    /**
     * check if MTK_SHARE_MODEM_SUPPORT is turned on or not
     */
    public static final int MTK_SHARE_MODEM_SUPPORT = 2;
    /**
     * check if MTK_SHARE_MODEM_CURRENT is turned on or not
     */
    public static final int MTK_SHARE_MODEM_CURRENT = 2;
    /**
     * check if MTK_EAP_SIM_AKA is turned on or not
     */
    public static final boolean MTK_EAP_SIM_AKA = true;
    /**
     * check if MTK_LOG2SERVER_APP is turned on or not
     */
    public static final boolean MTK_LOG2SERVER_APP = false;
    /**
     * check if MTK_FM_RECORDING_SUPPORT is turned on or not
     */
    public static final boolean MTK_FM_RECORDING_SUPPORT = true;
    /**
     * check if MTK_AVI_PLAYBACK_SUPPORT is turned on or not
     */
    public static final boolean MTK_AVI_PLAYBACK_SUPPORT = true;
    /**
     * check if MTK_AUDIO_APE_SUPPORT is turned on or not
     */
    public static final boolean MTK_AUDIO_APE_SUPPORT = true;
    /**
     * check if MTK_FLV_PLAYBACK_SUPPORT is turned on or not
     */
    public static final boolean MTK_FLV_PLAYBACK_SUPPORT = true;
    /**
     * check if MTK_WML_SUPPORT is turned on or not
     */
    public static final boolean MTK_WML_SUPPORT = true;
    /**
     * check if MTK_TB_APP_LANDSCAPE_SUPPORT is turned on or not
     */
    public static final boolean MTK_TB_APP_LANDSCAPE_SUPPORT = false;
    /**
     * check if HAVE_VORBISENC_FEATURE is turned on or not
     */
    public static final boolean HAVE_VORBISENC_FEATURE = true;
    /**
     * check if MTK_FD_FORCE_REL_SUPPORT is turned on or not
     */
    public static final boolean MTK_FD_FORCE_REL_SUPPORT = true;
    /**
     * check if MTK_BRAZIL_CUSTOMIZATION is turned on or not
     */
    public static final boolean MTK_BRAZIL_CUSTOMIZATION = false;
    /**
     * check if MTK_BRAZIL_CUSTOMIZATION_CLARO is turned on or not
     */
    public static final boolean MTK_BRAZIL_CUSTOMIZATION_CLARO = false;
    /**
     * check if MTK_BRAZIL_CUSTOMIZATION_VIVO is turned on or not
     */
    public static final boolean MTK_BRAZIL_CUSTOMIZATION_VIVO = false;
    /**
     * check if MTK_WMV_PLAYBACK_SUPPORT is turned on or not
     */
    public static final boolean MTK_WMV_PLAYBACK_SUPPORT = true;
    /**
     * check if MTK_HDMI_SUPPORT is turned on or not
     */
    public static final boolean MTK_HDMI_SUPPORT = false;
    /**
     * check if HAVE_AEE_FEATURE is turned on or not
     */
    public static final boolean HAVE_AEE_FEATURE = true;
    /**
     * check if MTK_FOTA_ENTRY is turned on or not
     */
    public static final boolean MTK_FOTA_ENTRY = false;
    /**
     * check if MTK_SCOMO_ENTRY is turned on or not
     */
    public static final boolean MTK_SCOMO_ENTRY = false;
    /**
     * check if MTK_OGM_PLAYBACK_SUPPORT is turned on or not
     */
    public static final boolean MTK_OGM_PLAYBACK_SUPPORT = false;
    /**
     * check if MTK_MTKPS_PLAYBACK_SUPPORT is turned on or not
     */
    public static final boolean MTK_MTKPS_PLAYBACK_SUPPORT = false;
    /**
     * check if MTK_SEND_RR_SUPPORT is turned on or not
     */
    public static final boolean MTK_SEND_RR_SUPPORT = true;
    /**
     * check if MTK_RAT_WCDMA_PREFERRED is turned on or not
     */
    public static final boolean MTK_RAT_WCDMA_PREFERRED = true;
    /**
     * check if MTK_SMSREG_APP is turned on or not
     */
    public static final boolean MTK_SMSREG_APP = false;
    /**
     * check if MTK_FM_RX_SUPPORT is turned on or not
     */
    public static final boolean MTK_FM_RX_SUPPORT = true;
    /**
     * check if MTK_DEFAULT_DATA_OFF is turned on or not
     */
    public static final boolean MTK_DEFAULT_DATA_OFF = false;
    /**
     * check if MTK_TB_APP_CALL_FORCE_SPEAKER_ON is turned on or not
     */
    public static final boolean MTK_TB_APP_CALL_FORCE_SPEAKER_ON = false;
    /**
     * check if MTK_EMMC_SUPPORT is turned on or not
     */
    public static final boolean MTK_EMMC_SUPPORT = true;
    /**
     * check if MTK_SIM_RECOVERY is turned on or not
     */
    public static final boolean MTK_SIM_RECOVERY = true;
    /**
     * check if MTK_CAMCORDER_PROFILE_MID_MP4 is turned on or not
     */
    public static final boolean MTK_CAMCORDER_PROFILE_MID_MP4 = false;
    /**
     * check if MTK_DISPLAY_HIGH_RESOLUTION is turned on or not
     */
    public static final boolean MTK_DISPLAY_HIGH_RESOLUTION = false;
    /**
     * check if MTK_AUDIO_HD_REC_SUPPORT is turned on or not
     */
    public static final boolean MTK_AUDIO_HD_REC_SUPPORT = true;
    /**
     * check if MTK_LAUNCHER_UNREAD_SUPPORT is turned on or not
     */
    public static final boolean MTK_LAUNCHER_UNREAD_SUPPORT = true;
    /**
     * check if MTK_FM_50KHZ_SUPPORT is turned on or not
     */
    public static final boolean MTK_FM_50KHZ_SUPPORT = false;
    /**
     * check if MTK_S3D_SUPPORT is turned on or not
     */
    public static final boolean MTK_S3D_SUPPORT = false;
    /**
     * check if MTK_ADUPS_FOTA_SUPPORT is turned on or not
     */
    public static final boolean MTK_ADUPS_FOTA_SUPPORT = true;
    /**
     * check if MTK_ADUPS_FOTA_WITH_ICON is turned on or not
     */
    public static final boolean MTK_ADUPS_FOTA_WITH_ICON = false;
    /**
     * check if MTK_BSP_PACKAGE is turned on or not
     */
    public static final boolean MTK_BSP_PACKAGE = false;
    /**
     * check if MTK_TETHERINGIPV6_SUPPORT is turned on or not
     */
    public static final boolean MTK_TETHERINGIPV6_SUPPORT = true;
    /**
     * check if MTK_PHONE_NUMBER_GEODESCRIPTION is turned on or not
     */
    public static final boolean MTK_PHONE_NUMBER_GEODESCRIPTION = true;
    /**
     * check if MTK_AUDIOPROFILE_SELECT_MMS_RINGTONE_SUPPORT is turned on or not
     */
    public static final boolean MTK_AUDIOPROFILE_SELECT_MMS_RINGTONE_SUPPORT = false;
    /**
     * check if MTK_LOG2SERVER_INTERNAL is turned on or not
     */
    public static final boolean MTK_LOG2SERVER_INTERNAL = false;
    /**
     * check if MTK_DT_SUPPORT is turned on or not
     */
    public static final boolean MTK_DT_SUPPORT = false;
    /**
     * check if EVDO_DT_SUPPORT is turned on or not
     */
    public static final boolean EVDO_DT_SUPPORT = false;
    /**
     * check if EVDO_DT_VIA_SUPPORT is turned on or not
     */
    public static final boolean EVDO_DT_VIA_SUPPORT = false;
    /**
     * check if MTK_SHARED_SDCARD is turned on or not
     */
    public static final boolean MTK_SHARED_SDCARD = false;
    /**
     * check if MTK_2SDCARD_SWAP is turned on or not
     */
    public static final boolean MTK_2SDCARD_SWAP = true;
    /**
     * check if ENCRY_PARTITION_SUPPORT is turned on or not
     */
    public static final boolean ENCRY_PARTITION_SUPPORT = false;
    /**
     * check if MTK_IMEI_LOCK is turned on or not
     */
    public static final boolean MTK_IMEI_LOCK = false;
    /**
     * check if MTK_ENS_SUPPORT is turned on or not
     */
    public static final boolean MTK_ENS_SUPPORT = false;
    /**
     * check if MTK_RAT_BALANCING is turned on or not
     */
    public static final boolean MTK_RAT_BALANCING = false;
    /**
     * check if MTK_MVNO_SUPPORT is turned on or not
     */
    public static final boolean MTK_MVNO_SUPPORT = true;
    /**
     * check if MTK_ACMT_DEBUG is turned on or not
     */
    public static final boolean MTK_ACMT_DEBUG = false;
    /**
     * check if MTK_TB_HW_DEBUG is turned on or not
     */
    public static final boolean MTK_TB_HW_DEBUG = false;
    /**
     * check if MTK_VSS_SUPPORT is turned on or not
     */
    public static final boolean MTK_VSS_SUPPORT = true;
    /**
     * check if MTK_FSCK_MSDOS_MTK is turned on or not
     */
    public static final boolean MTK_FSCK_MSDOS_MTK = false;
    /**
     * check if WIFI_WPS_PIN_FROM_AP is turned on or not
     */
    public static final boolean WIFI_WPS_PIN_FROM_AP = false;
    /**
     * check if WIFI_WEP_KEY_ID_SET is turned on or not
     */
    public static final boolean WIFI_WEP_KEY_ID_SET = false;
    /**
     * check if MTK_ENABLE_VIDEO_EDITOR is turned on or not
     */
    public static final boolean MTK_ENABLE_VIDEO_EDITOR = true;
    /**
     * check if OP01_CTS_COMPATIBLE is turned on or not
     */
    public static final boolean OP01_CTS_COMPATIBLE = false;
    /**
     * check if MTK_ENABLE_MD1 is turned on or not
     */
    public static final boolean MTK_ENABLE_MD1 = true;
    /**
     * check if MTK_ENABLE_MD2 is turned on or not
     */
    public static final boolean MTK_ENABLE_MD2 = false;
    /**
     * check if MTK_NETWORK_TYPE_ALWAYS_ON is turned on or not
     */
    public static final boolean MTK_NETWORK_TYPE_ALWAYS_ON = false;
    /**
     * check if MTK_EMMC_DISCARD is turned on or not
     */
    public static final boolean MTK_EMMC_DISCARD = false;
    /**
     * check if HAVE_CMMB_FEATURE is turned on or not
     */
    public static final boolean HAVE_CMMB_FEATURE = false;
    /**
     * check if MTK_NFC_SUPPORT is turned on or not
     */
    public static final boolean MTK_NFC_SUPPORT = false;
    /**
     * check if MTK_NFC_MT6605 is turned on or not
     */
    public static final boolean MTK_NFC_MT6605 = false;
    /**
     * check if MTK_NFC_MSR3110 is turned on or not
     */
    public static final boolean MTK_NFC_MSR3110 = false;
    /**
     * check if MTK_NFC_ADDON_SUPPORT is turned on or not
     */
    public static final boolean MTK_NFC_ADDON_SUPPORT = false;
    /**
     * check if MTK_NFC_APP_SUPPORT is turned on or not
     */
    public static final boolean MTK_NFC_APP_SUPPORT = false;
    /**
     * check if MTK_BENCHMARK_BOOST_TP is turned on or not
     */
    public static final boolean MTK_BENCHMARK_BOOST_TP = false;
    /**
     * check if MTK_FLIGHT_MODE_POWER_OFF_MD is turned on or not
     */
    public static final boolean MTK_FLIGHT_MODE_POWER_OFF_MD = true;
    /**
     * check if MTK_DATAUSAGE_SUPPORT is turned on or not
     */
    public static final boolean MTK_DATAUSAGE_SUPPORT = true;
    /**
     * check if NATIVE_AUDIO_PREPROCESS_ENABLE is turned on or not
     */
    public static final boolean NATIVE_AUDIO_PREPROCESS_ENABLE = true;
    /**
     * check if MTK_AAL_SUPPORT is turned on or not
     */
    public static final boolean MTK_AAL_SUPPORT = false;
    /**
     * check if MTK_TETHERING_EEM_SUPPORT is turned on or not
     */
    public static final boolean MTK_TETHERING_EEM_SUPPORT = false;
    /**
     * check if MTK_WFD_SUPPORT is turned on or not
     */
    public static final boolean MTK_WFD_SUPPORT = true;
    /**
     * check if MTK_BEAM_PLUS_SUPPORT is turned on or not
     */
    public static final boolean MTK_BEAM_PLUS_SUPPORT = false;
    /**
     * check if MTK_MT8193_HDMI_SUPPORT is turned on or not
     */
    public static final boolean MTK_MT8193_HDMI_SUPPORT = false;
    /**
     * check if MTK_GEMINI_3SIM_SUPPORT is turned on or not
     */
    public static final boolean MTK_GEMINI_3SIM_SUPPORT = false;
    /**
     * check if MTK_GEMINI_4SIM_SUPPORT is turned on or not
     */
    public static final boolean MTK_GEMINI_4SIM_SUPPORT = false;
    /**
     * check if MTK_WEB_NOTIFICATION_SUPPORT is turned on or not
     */
    public static final boolean MTK_WEB_NOTIFICATION_SUPPORT = true;
    /**
     * check if HAVE_ADPCMENCODE_FEATURE is turned on or not
     */
    public static final boolean HAVE_ADPCMENCODE_FEATURE = true;
    /**
     * check if MTK_SYSTEM_UPDATE_SUPPORT is turned on or not
     */
    public static final boolean MTK_SYSTEM_UPDATE_SUPPORT = false;
    /**
     * check if MTK_USES_VR_DYNAMIC_QUALITY_MECHANISM is turned on or not
     */
    public static final boolean MTK_USES_VR_DYNAMIC_QUALITY_MECHANISM = true;
    /**
     * check if MTK_SD_SUPPORT is turned on or not
     */
    public static final boolean MTK_SD_SUPPORT = true;
    /**
     * check if MTK_SIM_HOT_SWAP is turned on or not
     */
    public static final boolean MTK_SIM_HOT_SWAP = true;
    /**
     * check if MTK_VIDEO_THUMBNAIL_PLAY_SUPPORT is turned on or not
     */
    public static final boolean MTK_VIDEO_THUMBNAIL_PLAY_SUPPORT = true;
    /**
     * check if MTK_RADIOOFF_POWER_OFF_MD is turned on or not
     */
    public static final boolean MTK_RADIOOFF_POWER_OFF_MD = false;
    /**
     * check if MTK_BIP_SCWS is turned on or not
     */
    public static final boolean MTK_BIP_SCWS = false;
    /**
     * check if MTK_CTPPPOE_SUPPORT is turned on or not
     */
    public static final boolean MTK_CTPPPOE_SUPPORT = false;
    /**
     * check if MTK_IPV6_TETHER_PD_MODE is turned on or not
     */
    public static final boolean MTK_IPV6_TETHER_PD_MODE = false;
    /**
     * check if MTK_CACHE_MERGE_SUPPORT is turned on or not
     */
    public static final boolean MTK_CACHE_MERGE_SUPPORT = false;
    /**
     * check if MTK_FAT_ON_NAND is turned on or not
     */
    public static final boolean MTK_FAT_ON_NAND = false;
    /**
     * check if MTK_LAUNCH_TIME_OPTIMIZE is turned on or not
     */
    public static final boolean MTK_LAUNCH_TIME_OPTIMIZE = false;
    /**
     * check if MTK_LCA_RAM_OPTIMIZE is turned on or not
     */
    public static final boolean MTK_LCA_RAM_OPTIMIZE = false;
    /**
     * check if MTK_LCA_ROM_OPTIMIZE is turned on or not
     */
    public static final boolean MTK_LCA_ROM_OPTIMIZE = false;
    /**
     * check if MTK_TELEPHONY_MODE is turned on or not
     */
    public static final int MTK_TELEPHONY_MODE = 1;
    /**
     * check if MTK_MDM_LAWMO is turned on or not
     */
    public static final boolean MTK_MDM_LAWMO = false;
    /**
     * check if MTK_MDM_FUMO is turned on or not
     */
    public static final boolean MTK_MDM_FUMO = false;
    /**
     * check if MTK_MDM_SCOMO is turned on or not
     */
    public static final boolean MTK_MDM_SCOMO = false;
    /**
     * check if MTK_MAV_PLAYBACK_SUPPORT is turned on or not
     */
    public static final boolean MTK_MAV_PLAYBACK_SUPPORT = true;
    /**
     * check if MTK_MULTISIM_RINGTONE_SUPPORT is turned on or not
     */
    public static final boolean MTK_MULTISIM_RINGTONE_SUPPORT = false;
    /**
     * check if MTK_MT8193_HDCP_SUPPORT is turned on or not
     */
    public static final boolean MTK_MT8193_HDCP_SUPPORT = false;
    /**
     * check if MTK_CDS_EM_SUPPORT is turned on or not
     */
    public static final boolean MTK_CDS_EM_SUPPORT = true;
    /**
     * check if MTK_STREAMING_VIDEO_SUPPORT is turned on or not
     */
    public static final boolean MTK_STREAMING_VIDEO_SUPPORT = false;
    /**
     * check if MTK_NO_NEED_USB_LED is turned on or not
     */
    public static final boolean MTK_NO_NEED_USB_LED = true;
    /**
     * check if PURE_AP_USE_EXTERNAL_MODEM is turned on or not
     */
    public static final boolean PURE_AP_USE_EXTERNAL_MODEM = false;
    /**
     * check if MTK_SHOW_MSENSOR_TOAST_SUPPORT is turned on or not
     */
    public static final boolean MTK_SHOW_MSENSOR_TOAST_SUPPORT = true;
    /**
     * check if MTK_WFD_HDCP_TX_SUPPORT is turned on or not
     */
    public static final boolean MTK_WFD_HDCP_TX_SUPPORT = false;
    /**
     * check if MTK_NFC_OMAAC_SUPPORT is turned on or not
     */
    public static final boolean MTK_NFC_OMAAC_SUPPORT = false;
    /**
     * check if MTK_NFC_OMAAC_CMCC is turned on or not
     */
    public static final boolean MTK_NFC_OMAAC_CMCC = true;
    /**
     * check if MTK_WORLD_PHONE is turned on or not
     */
    public static final boolean MTK_WORLD_PHONE = false;
    /**
     * check if MTK_NO_TRAN_ANIM is turned on or not
     */
    public static final boolean MTK_NO_TRAN_ANIM = false;
    /**
     * check if MTK_PERFSERVICE_SUPPORT is turned on or not
     */
    public static final boolean MTK_PERFSERVICE_SUPPORT = true;
    /**
     * check if MTK_HW_KEY_REMAPPING is turned on or not
     */
    public static final boolean MTK_HW_KEY_REMAPPING = false;
    /**
     * check if MTK_AUDIO_CHANGE_SUPPORT is turned on or not
     */
    public static final boolean MTK_AUDIO_CHANGE_SUPPORT = false;
    /**
     * check if MTK_LOW_BAND_TRAN_ANIM is turned on or not
     */
    public static final boolean MTK_LOW_BAND_TRAN_ANIM = false;
    /**
     * check if MTK_HDMI_HDCP_SUPPORT is turned on or not
     */
    public static final boolean MTK_HDMI_HDCP_SUPPORT = false;
    /**
     * check if MTK_INTERNAL_HDMI_SUPPORT is turned on or not
     */
    public static final boolean MTK_INTERNAL_HDMI_SUPPORT = false;
    /**
     * check if MTK_INTERNAL_MHL_SUPPORT is turned on or not
     */
    public static final boolean MTK_INTERNAL_MHL_SUPPORT = false;
    /**
     * check if MTK_OWNER_SDCARD_ONLY_SUPPORT is turned on or not
     */
    public static final boolean MTK_OWNER_SDCARD_ONLY_SUPPORT = false;
    /**
     * check if MTK_ONLY_OWNER_SIM_SUPPORT is turned on or not
     */
    public static final boolean MTK_ONLY_OWNER_SIM_SUPPORT = false;
    /**
     * check if MTK_SIM_HOT_SWAP_COMMON_SLOT is turned on or not
     */
    public static final boolean MTK_SIM_HOT_SWAP_COMMON_SLOT = false;
    /**
     * check if MTK_AUTOIP_SUPPORT is turned on or not
     */
    public static final boolean MTK_AUTOIP_SUPPORT = false;
    /**
     * check if MTK_SEC_WFD_VIDEO_PATH_SUPPORT is turned on or not
     */
    public static final boolean MTK_SEC_WFD_VIDEO_PATH_SUPPORT = false;
    /**
     * check if MTK_CTA_SET is turned on or not
     */
    public static final boolean MTK_CTA_SET = true;
    /**
     * check if MTK_CTSC_MTBF_INTERNAL_SUPPORT is turned on or not
     */
    public static final boolean MTK_CTSC_MTBF_INTERNAL_SUPPORT = false;
    /**
     * check if MTK_3GDONGLE_SUPPORT is turned on or not
     */
    public static final boolean MTK_3GDONGLE_SUPPORT = false;
    /**
     * check if MTK_DEVREG_APP is turned on or not
     */
    public static final boolean MTK_DEVREG_APP = false;
    /**
     * check if EVDO_IR_SUPPORT is turned on or not
     */
    public static final boolean EVDO_IR_SUPPORT = false;
    /**
     * check if MTK_MULTI_PARTITION_MOUNT_ONLY_SUPPORT is turned on or not
     */
    public static final boolean MTK_MULTI_PARTITION_MOUNT_ONLY_SUPPORT = false;
    /**
     * check if MTK_WIFI_CALLING_RIL_SUPPORT is turned on or not
     */
    public static final boolean MTK_WIFI_CALLING_RIL_SUPPORT = false;
    /**
     * check if MTK_TABLET_PLUGIN_BUILD is turned on or not
     */
    public static final boolean MTK_TABLET_PLUGIN_BUILD = false;
    /**
     * check if MTK_DRM_KEY_MNG_SUPPORT is turned on or not
     */
    public static final boolean MTK_DRM_KEY_MNG_SUPPORT = false;
    /**
     * check if MTK_OVERLAY_ENGINE_SUPPORT is turned on or not
     */
    public static final boolean MTK_OVERLAY_ENGINE_SUPPORT = false;
    /**
     * check if MTK_DOLBY_DAP_SUPPORT is turned on or not
     */
    public static final boolean MTK_DOLBY_DAP_SUPPORT = false;
    /**
     * check if FPGA_EARLY_PORTING is turned on or not
     */
    public static final boolean FPGA_EARLY_PORTING = false;
    /**
     * check if MTK_DT_3G_SWITCH is turned on or not
     */
    public static final boolean MTK_DT_3G_SWITCH = false;
    /**
     * check if MTK_WFD_VIDEO_FORMAT is turned on or not
     */
    public static final int MTK_WFD_VIDEO_FORMAT = 1;
    /**
     * check if MTK_MOTION_TRACK_SUPPORT is turned on or not
     */
    public static final boolean MTK_MOTION_TRACK_SUPPORT = true;
    /**
     * check if MTK_VIDEO_HEVC_SUPPORT is turned on or not
     */
    public static final boolean MTK_VIDEO_HEVC_SUPPORT = true;
    /**
     * check if MTK_MOBILE_MANAGEMENT is turned on or not
     */
    public static final boolean MTK_MOBILE_MANAGEMENT = true;
    /**
     * check if MTK_CLEARMOTION_SUPPORT is turned on or not
     */
    public static final boolean MTK_CLEARMOTION_SUPPORT = true;
    /**
     * check if MTK_DFO_RESOLUTION_SUPPORT is turned on or not
     */
    public static final boolean MTK_DFO_RESOLUTION_SUPPORT = false;
    /**
     * check if MTK_LIVE_PHOTO_SUPPORT is turned on or not
     */
    public static final boolean MTK_LIVE_PHOTO_SUPPORT = false;
    /**
     * check if MTK_PASSPOINT_R1_SUPPORT is turned on or not
     */
    public static final boolean MTK_PASSPOINT_R1_SUPPORT = true;
    /**
     * check if MTK_TRANSPARENT_BAR_SUPPORT is turned on or not
     */
    public static final boolean MTK_TRANSPARENT_BAR_SUPPORT = false;
    /**
     * check if MTK_CAMERA_OT_SUPPORT is turned on or not
     */
    public static final boolean MTK_CAMERA_OT_SUPPORT = true;
    /**
     * check if MTK_SMARTBOOK_SUPPORT is turned on or not
     */
    public static final boolean MTK_SMARTBOOK_SUPPORT = false;
    /**
     * check if MTK_UMTS_TDD128_MODE is turned on or not
     */
    public static final boolean MTK_UMTS_TDD128_MODE = false;
    /**
     * check if MTK_CHIPTEST_INT is turned on or not
     */
    public static final boolean MTK_CHIPTEST_INT = false;
    /**
     * check if MTK_USER_ROOT_SWITCH is turned on or not
     */
    public static final boolean MTK_USER_ROOT_SWITCH = false;
    /**
     * check if MTK_BESLOUDNESS_SUPPORT is turned on or not
     */
    public static final boolean MTK_BESLOUDNESS_SUPPORT = true;
    /**
     * check if MTK_SAFEMEDIA_SUPPORT is turned on or not
     */
    public static final boolean MTK_SAFEMEDIA_SUPPORT = false;
    /**
     * check if MTK_SINGLE_IMEI is turned on or not
     */
    public static final boolean MTK_SINGLE_IMEI = false;
    /**
     * check if MTK_SDIOAUTOK_SUPPORT is turned on or not
     */
    public static final boolean MTK_SDIOAUTOK_SUPPORT = false;
    /**
     * check if MTK_RILD_READ_IMSI is turned on or not
     */
    public static final boolean MTK_RILD_READ_IMSI = false;
    /**
     * check if VANZO_DOUBLE_CLICK_WAKEUP is turned on or not
     */
    public static final boolean VANZO_DOUBLE_CLICK_WAKEUP = false;
    /**
     * check if VANZO_TOUCHPANEL_GESTURES_SUPPORT is turned on or not
     */
    public static final boolean VANZO_TOUCHPANEL_GESTURES_SUPPORT = false;
}
