/* generated by mediatek */

package com.mediatek.common.featureoption;

public final class IMEFeatureOption
{

	public static final String[] PRODUCT_LOCALES=
	{
		"en_US",
		"fr_FR",
		"it_IT",
		"es_ES",
		"de_DE",
		"nl_NL",
		"cs_CZ",
		"pl_PL",
		"ja_JP",
		"zh_TW",
		"zh_CN",
		"ru_RU",
		"ko_KR",
		"nb_NO",
		"es_US",
		"da_DK",
		"el_GR",
		"tr_TR",
		"pt_PT",
		"pt_BR",
		"rm_CH",
		"sv_SE",
		"bg_BG",
		"ca_ES",
		"en_GB",
		"fi_FI",
		"hi_IN",
		"hr_HR",
		"hu_HU",
		"in_ID",
		"iw_IL",
		"lt_LT",
		"lv_LV",
		"ro_RO",
		"sk_SK",
		"sl_SI",
		"sr_RS",
		"uk_UA",
		"vi_VN",
		"tl_PH",
		"ar_EG",
		"fa_IR",
		"th_TH",
		"sw_TZ",
		"ms_MY",
		"af_ZA",
		"zu_ZA",
		"am_ET",
		"hi_IN",
	};
	public static final String DEFAULT_INPUT_METHOD="com.sohu.inputmethod.sogou.SogouIME";

	public static final String[] DEFAULT_LATIN_IME_LANGUAGES=
	{
		"en-US",
	};
	public static final boolean 	SYS_LOCALE_JA = 	true;
	public static final boolean 	SYS_LOCALE_CA = 	true;
	public static final boolean 	SYS_LOCALE_ZH_CN = 	true;
	public static final boolean 	SYS_LOCALE_DA_DK = 	true;
	public static final boolean 	SYS_LOCALE_AR_EG = 	true;
	public static final boolean 	SYS_LOCALE_NB = 	true;
	public static final boolean 	SYS_LOCALE_SW = 	true;
	public static final boolean 	SYS_LOCALE_AF = 	true;
	public static final boolean 	SYS_LOCALE_RO = 	true;
	public static final boolean 	SYS_LOCALE_BG_BG = 	true;
	public static final boolean 	SYS_LOCALE_SV = 	true;
	public static final boolean 	SYS_LOCALE_SL = 	true;
	public static final boolean 	SYS_LOCALE_IW_IL = 	true;
	public static final boolean 	SYS_LOCALE_DA = 	true;
	public static final boolean 	SYS_LOCALE_ZU = 	true;
	public static final boolean 	SYS_LOCALE_BG = 	true;
	public static final boolean 	SYS_LOCALE_JA_JP = 	true;
	public static final boolean 	SYS_LOCALE_MS_MY = 	true;
	public static final boolean 	SYS_LOCALE_LV_LV = 	true;
	public static final boolean 	SYS_LOCALE_RM = 	true;
	public static final boolean 	SYS_LOCALE_CS_CZ = 	true;
	public static final boolean 	SYS_LOCALE_LT_LT = 	true;
	public static final boolean 	SYS_LOCALE_FR = 	true;
	public static final boolean 	SYS_LOCALE_SR_RS = 	true;
	public static final boolean 	SYS_LOCALE_EL = 	true;
	public static final boolean 	SYS_LOCALE_HU = 	true;
	public static final boolean 	SYS_LOCALE_PL = 	true;
	public static final boolean 	SYS_LOCALE_HI_IN = 	true;
	public static final boolean 	SYS_LOCALE_TL_PH = 	true;
	public static final boolean 	SYS_LOCALE_DE_DE = 	true;
	public static final boolean 	SYS_LOCALE_PT = 	true;
	public static final boolean 	SYS_LOCALE_AR = 	true;
	public static final boolean 	SYS_LOCALE_NL_NL = 	true;
	public static final boolean 	SYS_LOCALE_EN_US = 	true;
	public static final boolean 	SYS_LOCALE_ES_ES = 	true;
	public static final boolean 	SYS_LOCALE_RM_CH = 	true;
	public static final boolean 	SYS_LOCALE_ZH = 	true;
	public static final boolean 	SYS_LOCALE_UK_UA = 	true;
	public static final boolean 	SYS_LOCALE_FI = 	true;
	public static final boolean 	SYS_LOCALE_IN_ID = 	true;
	public static final boolean 	SYS_LOCALE_TR = 	true;
	public static final boolean 	SYS_LOCALE_AM = 	true;
	public static final boolean 	SYS_LOCALE_RU = 	true;
	public static final boolean 	SYS_LOCALE_TR_TR = 	true;
	public static final boolean 	SYS_LOCALE_ES = 	true;
	public static final boolean 	SYS_LOCALE_LT = 	true;
	public static final boolean 	SYS_LOCALE_DE = 	true;
	public static final boolean 	SYS_LOCALE_EN = 	true;
	public static final boolean 	SYS_LOCALE_KO_KR = 	true;
	public static final boolean 	SYS_LOCALE_TH_TH = 	true;
	public static final boolean 	SYS_LOCALE_CS = 	true;
	public static final boolean 	SYS_LOCALE_SW_TZ = 	true;
	public static final boolean 	SYS_LOCALE_LV = 	true;
	public static final boolean 	SYS_LOCALE_NL = 	true;
	public static final boolean 	SYS_LOCALE_FR_FR = 	true;
	public static final boolean 	SYS_LOCALE_KO = 	true;
	public static final boolean 	SYS_LOCALE_IT_IT = 	true;
	public static final boolean 	SYS_LOCALE_HR_HR = 	true;
	public static final boolean 	SYS_LOCALE_VI = 	true;
	public static final boolean 	SYS_LOCALE_EL_GR = 	true;
	public static final boolean 	SYS_LOCALE_MS = 	true;
	public static final boolean 	SYS_LOCALE_TL = 	true;
	public static final boolean 	SYS_LOCALE_SV_SE = 	true;
	public static final boolean 	SYS_LOCALE_SK_SK = 	true;
	public static final boolean 	SYS_LOCALE_IW = 	true;
	public static final boolean 	SYS_LOCALE_NB_NO = 	true;
	public static final boolean 	SYS_LOCALE_FA_IR = 	true;
	public static final boolean 	SYS_LOCALE_ZU_ZA = 	true;
	public static final boolean 	SYS_LOCALE_ZH_TW = 	true;
	public static final boolean 	SYS_LOCALE_EN_GB = 	true;
	public static final boolean 	SYS_LOCALE_VI_VN = 	true;
	public static final boolean 	SYS_LOCALE_FI_FI = 	true;
	public static final boolean 	SYS_LOCALE_AM_ET = 	true;
	public static final boolean 	SYS_LOCALE_PT_BR = 	true;
	public static final boolean 	SYS_LOCALE_SL_SI = 	true;
	public static final boolean 	SYS_LOCALE_FA = 	true;
	public static final boolean 	SYS_LOCALE_IN = 	true;
	public static final boolean 	SYS_LOCALE_RO_RO = 	true;
	public static final boolean 	SYS_LOCALE_PL_PL = 	true;
	public static final boolean 	SYS_LOCALE_IT = 	true;
	public static final boolean 	SYS_LOCALE_UK = 	true;
	public static final boolean 	SYS_LOCALE_SR = 	true;
	public static final boolean 	SYS_LOCALE_ES_US = 	true;
	public static final boolean 	SYS_LOCALE_TH = 	true;
	public static final boolean 	SYS_LOCALE_PT_PT = 	true;
	public static final boolean 	SYS_LOCALE_HU_HU = 	true;
	public static final boolean 	SYS_LOCALE_CA_ES = 	true;
	public static final boolean 	SYS_LOCALE_HI = 	true;
	public static final boolean 	SYS_LOCALE_RU_RU = 	true;
	public static final boolean 	SYS_LOCALE_AF_ZA = 	true;
	public static final boolean 	SYS_LOCALE_SK = 	true;
	public static final boolean 	SYS_LOCALE_HR = 	true;
	public static final boolean 	SYS_LOCALE_DE_CH = 	false;
	public static final boolean 	SYS_LOCALE_FR_CH = 	false;
	public static final boolean 	SYS_LOCALE_DE_LI = 	false;
	public static final boolean 	SYS_LOCALE_FR_CA = 	false;
	public static final boolean 	SYS_LOCALE_EN_SG = 	false;
	public static final boolean 	SYS_LOCALE_IT_CH = 	false;
	public static final boolean 	SYS_LOCALE_EN_AU = 	false;
	public static final boolean 	SYS_LOCALE_DE_AT = 	false;
	public static final boolean 	SYS_LOCALE_FR_BE = 	false;
	public static final boolean 	SYS_LOCALE_EN_NZ = 	false;
	public static final boolean 	SYS_LOCALE_NL_BE = 	false;

	public static final boolean 	MTK_IME_RUSSIAN_SUPPORT = false;
	public static final boolean 	MTK_IME_SUPPORT = false;
	public static final boolean 	MTK_IME_ENGLISH_SUPPORT = true;
	public static final boolean 	MTK_IME_PINYIN_SUPPORT = true;
	public static final boolean 	MTK_IME_STROKE_SUPPORT = true;
	public static final boolean 	MTK_IME_HANDWRITING_SUPPORT = true;
	public static final boolean 	MTK_IME_ZHUYIN_SUPPORT = true;
	public static final boolean 	MTK_IME_FRENCH_SUPPORT = false;
	public static final boolean 	MTK_IME_GERMAN_SUPPORT = false;
	public static final boolean 	MTK_IME_SPANISH_SUPPORT = false;
	public static final boolean 	MTK_IME_ITALIAN_SUPPORT = false;
	public static final boolean 	MTK_IME_PORTUGUESE_SUPPORT = false;
	public static final boolean 	MTK_IME_TURKISH_SUPPORT = false;
	public static final boolean 	MTK_IME_INDONESIAN_SUPPORT = false;
	public static final boolean 	MTK_IME_MALAY_SUPPORT = false;
	public static final boolean 	MTK_IME_HINDI_SUPPORT = false;
	public static final boolean 	MTK_IME_ARABIC_SUPPORT = false;
	public static final boolean 	MTK_IME_THAI_SUPPORT = false;
	public static final boolean 	MTK_IME_VIETNAM_SUPPORT = false;
}
