/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6592. Copyright MediaTek Inc. (C) 2013.
 * Fri Dec 13 21:33:27 2013
 * Do Not Modify the File.
 */



#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/mt_pm_ldo.h>
#ifdef MTK_MT6333_SUPPORT
#include <mach/mt6333.h>
#endif
void pmu_drv_tool_customization_init(void)
{
    pmic_ldo_enable(MT6322_POWER_LDO_VM,KAL_FALSE);
    pmic_ldo_enable(MT6322_POWER_LDO_VRF18,KAL_FALSE);
    #ifdef MTK_MT6333_SUPPORT
mt6333_set_vcore_en(1);
#endif
    #ifdef MTK_MT6333_SUPPORT
mt6333_set_vmem_en(1);
#endif
}


