/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef _ANDROID_HARDWARE_MTK_CAMERA_PROFILE_H_
#define _ANDROID_HARDWARE_MTK_CAMERA_PROFILE_H_

#include <camera/MtkCameraMMP.h>

/**
  * @brief Camera profile event of the camera framework 
  */
typedef enum
{
    Event_Camera_Framework_Root     = EVENT_CAMERA_FRAMEWORK, 
    Event_CameraService,  
    Event_CS_connect,
	Event_CS_newMediaPlayer,
	Event_CS_newCamHwIF,
	Event_CS_newClient,
	Event_CS_getParameters,
	Event_CS_setParameters,
	Event_CS_setPreviewDisplay,
	Event_CS_sendCommand,
	Event_CS_startPreview,
	Event_CS_startRecording,
	Event_CS_takePicture,
	Event_CS_stopPreview,
	Event_CS_stopRecording,
	Event_CS_playSound,
	Event_CS_disconnect,
	Event_CS_disconnectWindow,
	Event_CS_releaseRecordingFrame,
	Event_CS_dataCallbackTimestamp,
}CPT_Camera_Framework_Event;

bool initCameraProfile();

////////////////////////////////////////////////////////////////////////////////
#endif  //  _ANDROID_HARDWARE_MTK_CAMERA_PROFILE_H_

